name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint code
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        run: npm i pnpm -g
      - name: Install dependencies
        run: pnpm install
      - name: Run lint and prettier
        run: pnpm format
