name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint code
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          run-install: true
          version: 9
      - name: Run lint and prettier
        run: pnpm format
